In [2]:
from operator import index

import numpy as np
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from statsmodels.stats.stattools import medcouple

plt.rcParams['figure.figsize'] = [15, 7]

In [3]:
df = pd.read_csv("./outlierDatasets/synthetic.csv")

In [4]:
X = df.iloc[:, 4:6]
y = df['outlier']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
le = LabelEncoder()
y_train = np.array(le.fit_transform(y_train))

In [7]:
X_train = np.array(X_train)

In [8]:
def main(X,y,n):
    nn = NearestNeighbors(n_neighbors=n)
    nn.fit(X, y)
    dist, knn = nn.kneighbors(X)  # returns N index neighbors including self
    return knn, dist

near, distReturn = main(X_train,y_train,10)

In [9]:
print(distReturn)

[[0.         0.04283727 0.07493529 ... 0.16289404 0.17268253 0.17529331]
 [0.         0.00293483 0.00396415 ... 0.00997794 0.01034337 0.01040541]
 [0.         0.00704806 0.00836768 ... 0.01816851 0.01852693 0.01970613]
 ...
 [0.         0.00834301 0.00871537 ... 0.01353472 0.01606579 0.01652162]
 [0.         0.00154475 0.00723877 ... 0.01520893 0.01648348 0.01859028]
 [0.         0.00374494 0.00729726 ... 0.01315824 0.0134085  0.01362817]]


In [10]:
def generateArr(newDist, median='median'):
    arr = []
    for x in newDist:  # finds the distance away from that point (index 0)
        if median == 'median':
            arr += [np.median(x)]
        elif median == 'sum': # min + median + max
            arr += [x[1]+np.max(x)+np.median(x)]
        elif median == 'max':
            arr += [np.max(x)]
        elif median == 'minMax':
            arr += [np.max(x)+x[1]]
        elif median == 'medMax':
            arr += [np.median(x)+np.max(x)]
        elif median == 'min':
            arr += [x[1]]
            

    return arr

arr = generateArr(distReturn, median="medMax")
print(arr)

[0.3146217984237124, 0.019027329343379525, 0.03246736444436799, 0.03160625826773192, 0.028474237033854495, 0.02910258935816971, 0.048496405402285225, 0.02909315334468314, 0.023752742971200492, 0.057394052338142654, 0.018210372983357884, 0.27205569674083513, 0.035066801688420336, 0.02627201107302413, 0.02144164381542711, 0.04267516771944266, 0.04600423314180242, 0.023258977448052623, 0.07447507025713251, 0.02516826192441168, 0.021084467493278237, 0.025353270906396514, 0.02756493481245951, 0.04151330059956869, 0.02515331590876238, 0.05573837835860802, 0.03056335441301858, 0.029582098251596235, 0.04990279203449849, 0.03141985548171354, 0.03302811828231157, 0.04757799647075833, 0.02551959707368244, 0.042485341598069534, 0.026148509224738214, 0.03162855071019826, 0.023762857194586567, 0.0334298110668838, 0.02386222388381358, 0.07841098491759471, 0.13285254064976232, 0.03728800049441431, 0.027671205198317596, 0.029355997800318192, 0.02809912042870978, 0.04874096122393047, 0.02994140548268529